### PR TITLE
Few fixes

### LINKED ISSUE #1148: omdb give a wrong seriesid
omdb give a wrong seriesid : seriesid = imdbid.

You can have a try on :
https://www.omdbapi.com/
imdbid = tt2916312
seriesid will be equal to imdbid

### PR DESCRIPTION
**Pull request by SurfaceS**
fix #1148
remove the bogus seriesIMDbID from omdb data mapper.

few fix names (imdbID/Spy) on media-video test to better identify spy.

### CODE REVIEW

File: src/controllers/media.ts [hunk 1]
```diff
@@ -256,6 +255,11 @@ export const getVideoV2 = async(ctx: ParameterizedContext): Promise<MediaMetadat
     try {
       openSubtitlesMetadata = await externalAPIHelper.getFromOpenSubtitles(osQuery, validation);
       imdbIdToSearch = imdbIdToSearch || openSubtitlesMetadata?.imdbID;
+      if (!title && !imdbID && !episodeNumbers && openSubtitlesMetadata?.type === 'episode') {
+        //here we now the osdbHash is for an episode and episode is not set
```
Comment (SubJunk) [inline src/controllers/media.ts:259]:
```suggestion
        //here we know the osdbHash is for an episode and episode is not set
```

**Review by SubJunk — APPROVED** [review]
